//
// Created by valeriisudakov on 11.09.20.
//

#ifndef TASKMANAGER_CLI_STATESCONTROLLERS_FINITESTATESMACHINESLIST_H_
#define TASKMANAGER_CLI_STATESCONTROLLERS_FINITESTATESMACHINESLIST_H_

enum class FiniteStateMachineID{
  INPUT_NAME,
  INPUT_LABEL,
  INPUT_DATE,
  INPUT_ID,
  POSTPONE,
  INPUT_TASK_PARAMS,
  INPUT_SUBTASK_PARAMS
};

#endif //TASKMANAGER_CLI_STATESCONTROLLERS_FINITESTATESMACHINESLIST_H_
