//
// Created by valeriisudakov on 28.08.20.
//

#ifndef TASKMANAGER_CLI_STATES_INPUTSTATES_INPUTSTATEOPERATIONRESULT_H_
#define TASKMANAGER_CLI_STATES_INPUTSTATES_INPUTSTATEOPERATIONRESULT_H_

enum class StateOperationResult{
  SUCCESS,
  INCORRECT_INPUT,
  FAIL,
  TASKS_LIST_EMPTY
};

#endif //TASKMANAGER_CLI_STATES_INPUTSTATES_INPUTSTATEOPERATIONRESULT_H_
